music_list = ['A cappella', 'Accelerando', 'Accessible', 'Adagio', 'Allegro',
    'Atonal', 'Baroque', 'Beat', 'Cadence', 'Cadenza', 'Cadenza', 'Canon',
    'Cantabile', 'Cantata', 'Capriccio', 'Carol', 'Castrato', 'Cavatina',
    'Chamber music', 'Chant', 'Choir', 'Chorale', 'Chord', 'Chord progression',
    'Chorus', 'Chromatic scale', 'Classical', 'Classicism', 'Clavier', 'Clef',
    'Coda', 'Concert master', 'Concerto', 'Conductor', 'Consonance',
    'Contralto', 'Counterpoint', 'Courante', 'Da Capo', 'Deceptive cadence',
    'Development', 'Dissonance', 'Drone', 'Duet', 'Dynamics', 'Elegy',
    'Encore', 'Energico', 'Enharmonic Interval', 'Ensemble', 'Espressivo',
    'Etude', 'Exposition', 'Expressionism', 'Falsetto', 'Fermata', 'Fifth',
    'Finale', 'Flat', 'Form', 'Forte', 'Fourth', 'Fugue', 'Galliard',
    'Gavotte', 'Glee', 'Glissando', 'Grandioso', 'Grave', 'Grazioso',
    'Gregorian Chant',
    'Harmony', 'Homophony', 'Hymn', 'Impromptu', 'Instrumentation',
    'Interlude',
    'Intermezzo', 'Interpretation', 'Interval', 'Intonation', 'Introduction',
    'Key', 'Key signature', 'Klangfarbenmelodie', 'Leading note', 'Legato',
    'Leitmotif', 'Libretto', 'Ligature', 'Madrigal', 'Maestro', 'Major',
    'March', 'Measure', 'Medley', 'Mezzo', 'Minor', 'Minuet', 'Modes',
    'Modulation', 'Monotone', 'Motif', 'Movement', 'Musette', 'Musicology',
    'Natural', 'Neoclassical', 'Nocturne', 'Nonet', 'Notation', 'Obbligato',
    'Octave', 'Octet', 'Opera', 'Operetta', 'Opus', 'Oratorio', 'Orchestra',
    'Orchestration', 'Ornaments', 'Ostinato', 'Overture', 'Parody', 'Part',
    'Partial', 'Partita', 'Pastoral', 'Pentatonic Scale', 'Phrase', 'Piano',
    'Pitch', 'Pizzicato', 'Polyphony', 'Polytonality', 'Portamento', 'Prelude',
    'Presto', 'Progression', 'Quadrille', 'Quartet', 'Quintet',
    'Recapitulation', 'Recital', 'Recitative', 'Reed', 'Refrain', 'Register',
    'Relative major and minor', 'Relative pitch', 'Renaissance', 'Reprise',
    'Requiem', 'Resonance', 'Rhythm', 'Ricercar', 'Rigaudon', 'Rococo',
    'Romantic', 'Rondo', 'Root', 'Round', 'Rubato', 'Scale', 'Scherzo',
    'Scordatura', 'Septet', 'Sequence', 'Serenade', 'Sextet', 'Sharp', 'Slide',
    'Slur', 'Sonata', 'Sonata form', 'Sonatina', 'Song cycle', 'Soprano',
    'Staccato', 'Staff', 'Stretto', 'String Quartet', 'Suite', 'Symphony',
    'System', 'Tablature', 'Temperament', 'Tempo', 'Tessitura', 'Theme',
    'Timbre', 'Time Signature', 'Tonal', 'Tonality', 'Tone', 'Tone less',
    'Tonic', 'Treble', 'Tremolo', 'Triad', 'Trill', 'Trio', 'Triple time',
    'Triplet', 'Tritone', 'Tune', 'Tuning', 'Tutti', 'Twelve-tone music',
    'Unison', 'Verismo', 'Vibrato', 'Virtuoso', 'Vivace', 'Voice',
    'Waltz', 'Whole note', 'Whole-tone scale']
